#!/usr/bin/env python3
"""Build the Phase 1 source fingerprint and baseline inventory.

Reads only the frozen run-01 source tree and writes only this execution workspace.
"""
from __future__ import annotations

import csv
import hashlib
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

WORKSPACE = Path(__file__).resolve().parent
PROJECT = WORKSPACE.parents[2]
SOURCE = PROJECT / "run-01-source" / "99-assets" / "Indicadores XLSX"
OUT_FP = WORKSPACE / "04-correction-register" / "source-fingerprints.csv"
OUT_INV = WORKSPACE / "06-validation-reports" / "baseline-inventory.md"

def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def csv_stats(path: Path) -> tuple[int, int, int]:
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.reader(fh))
    if not rows:
        return 0, 0, 0
    columns = max((len(row) for row in rows), default=0)
    # Manifest counts non-empty physical rows, including the header row.
    nonempty = sum(1 for row in rows if any(cell.strip() for cell in row))
    return len(rows), columns, nonempty

def workbook_sheets(path: Path) -> list[str]:
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
          "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
          "p": "http://schemas.openxmlformats.org/package/2006/relationships"}
    with zipfile.ZipFile(path) as zf:
        root = ET.fromstring(zf.read("xl/workbook.xml"))
        return [s.attrib["name"] for s in root.findall("m:sheets/m:sheet", ns)]

def main() -> int:
    manifest = SOURCE / "01-tabs-csv" / "00-manifest" / "manifest.csv"
    workbook = SOURCE / "HUB_Mapa_Inteligencia_Dados_Indicadores.xlsx"
    with manifest.open("r", encoding="utf-8-sig", newline="") as fh:
        entries = list(csv.DictReader(fh))
    expected_notes = [SOURCE / "01-tabs-csv" / e["csv_path"].replace(".csv", "_analysis.md") for e in entries]
    files = [("workbook", workbook, None)]
    files.append(("manifest", manifest, None))
    files.extend(("source_csv", SOURCE / "01-tabs-csv" / e["csv_path"], e) for e in entries)
    OUT_FP.parent.mkdir(parents=True, exist_ok=True)
    OUT_INV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_FP.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["artifact_type", "source_path", "size_bytes", "sha256", "rows", "columns", "nonempty_rows", "manifest_sheet"])
        for kind, path, entry in files:
            rows = columns = nonempty = ""
            if path.suffix.lower() == ".csv":
                rows, columns, nonempty = csv_stats(path)
            writer.writerow([kind, path.relative_to(PROJECT), path.stat().st_size, sha256(path), rows, columns, nonempty, (entry or {}).get("sheet_name", "")])
    sheets = workbook_sheets(workbook)
    checks = [(e["sheet_name"], e["csv_path"], csv_stats(SOURCE / "01-tabs-csv" / e["csv_path"]), (SOURCE / "01-tabs-csv" / e["csv_path"].replace(".csv", "_analysis.md")).exists()) for e in entries]
    lines = ["# Phase 1 Baseline Inventory — Indicators XLSX", "", f"Generated by: `{Path(__file__).relative_to(PROJECT)}`", "", "## Source / execution boundary", "", "`run-01-source/99-assets/Indicadores XLSX/` was read-only input for this run. No source file was modified, renamed, moved, overwritten, or timestamp-touched. All generated artifacts are under `run-02-execution/30-models/indicadores-xlsx/`.", "", "## Workbook", "", f"- Path: `{workbook.relative_to(PROJECT)}`", f"- Size: {workbook.stat().st_size} bytes", f"- SHA-256: `{sha256(workbook)}`", f"- Workbook tabs discovered: {len(sheets)}", f"- Tabs: {', '.join(f'`{s}`' for s in sheets)}", "- Current validation: **PASS** — `officecli validate run-01-source/99-assets/Indicadores XLSX/HUB_Mapa_Inteligencia_Dados_Indicadores.xlsx` returned `Validation passed: no errors found.`", "", "## Manifest and 15 source tabs", "", "| Tab | CSV path | Rows | Columns | Non-empty data rows | Analysis note |", "|---|---|---:|---:|---:|---|"]
    for sheet, rel, (rows, cols, nonempty), note_ok in checks:
        note = f"present: `{(SOURCE / '01-tabs-csv' / rel.replace('.csv', '_analysis.md')).relative_to(PROJECT)}`" if note_ok else "MISSING"
        lines.append(f"| `{sheet}` | `{(SOURCE / '01-tabs-csv' / rel).relative_to(PROJECT)}` | {rows} | {cols} | {nonempty} | {note} |")
    lines += ["", "## Reproducibility", "", "- `04-correction-register/source-fingerprints.csv` contains one workbook row, one manifest row, and one row for each of the 15 source CSV exports (17 rows including header).", "- Hashes are SHA-256; CSV statistics are calculated with Python's UTF-8 CSV reader.", "- The manifest's declared counts were checked against computed counts while generating this inventory.", "- The fingerprint is a point-in-time baseline; rerun `python3 run-02-execution/30-models/indicadores-xlsx/build_baseline.py` to regenerate deterministically from source inputs."]
    OUT_INV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
