/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  C2DSettingTab: () => C2DSettingTab,
  default: () => Canvas2DocumentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var path = __toESM(require("path"));
var DEFAULT_SETTINGS = {
  usefrontmatter: true,
  useedgelabels: true,
  autooverwrite: false
};
var C2DSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    let { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Include YAML frontmatter from embedded documents").setDesc("Makes metadata from embedded documents usable in target document").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.usefrontmatter).onChange(async (value) => {
        this.plugin.settings.usefrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include labels of canvas edges (connections)").setDesc("Makes connections descriptions usable in target document").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useedgelabels).onChange(async (value) => {
        this.plugin.settings.useedgelabels = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Overwrite existing target documents without confirmation").setDesc("User confirmation is not needed to overwrite existing target documents").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autooverwrite).onChange(async (value) => {
        this.plugin.settings.autooverwrite = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
var Canvas2DocumentPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new C2DSettingTab(this.app, this));
    if (this.app.vault.adapter instanceof import_obsidian.FileSystemAdapter) {
      this.fsadapter = this.app.vault.adapter;
    } else {
      return;
    }
    this.addCommand({
      id: "run-conversion",
      name: "Step 1 - Convert canvas to a longform document",
      callback: async () => {
        let selectedNodes = [];
        let totalNodes = 0;
        let selectedNodesCount = 0;
        let colorValues_length = 0;
        let nodesWithColorCount = 0;
        let nodesWithOutColorCount = 0;
        let colorCounts = /* @__PURE__ */ new Map();
        const canvasView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
        if ((canvasView == null ? void 0 : canvasView.getViewType()) == "canvas") {
          const canvas = canvasView.canvas;
          const selection = Array.from(canvas.selection);
          if (selection && selection.length > 0) {
            selectedNodes = selection.map(
              (node) => ({
                id: node.id,
                color: node.color
              })
            );
          } else {
            selectedNodes = [];
          }
          const canvStruct = await this.readCanvasStruct();
          if (canvStruct == false) {
            new import_obsidian.Notice(`this is not a canvas file`);
            return;
          }
          let [totalNodes2, selectedNodesCount2, colorValues_length2, nodesWithColorCount2, nodesWithOutColorCount2, colorCounts2, colorNodeIds, NoColorNodeIds, full_data] = await this.readCanvasData_pre(canvStruct, selectedNodes);
          const modal = new import_obsidian.Modal(this.app);
          modal.titleEl.setText("Canvas2Document conversion - step 1");
          const header = modal.contentEl.createDiv();
          header.addClass("modal-header");
          header.createEl("h2", { text: "Select conversion mode:" });
          header.createEl("p").innerHTML = "<em>Choose which nodes from your canvas you want to convert into the target document. You can select all nodes, only selected nodes, or filter by color tags.</em>";
          const radioGroup = modal.contentEl.createDiv();
          radioGroup.addClasses(["modal-content"]);
          let selectedOption = "all";
          const createRadioOption = (value, label) => {
            const container = radioGroup.createDiv();
            container.addClass("radio-container");
            const radio = container.createEl("input", { type: "radio", value });
            radio.name = "conversion-mode";
            radio.checked = value === selectedOption;
            radio.onchange = () => {
              selectedOption = value;
            };
            container.createEl("label", { text: label }).insertAfter(radio);
          };
          createRadioOption("all", `all - Convert all nodes  (${totalNodes2} total)`);
          createRadioOption("selected", `selected - Convert selected nodes only (${selectedNodesCount2} selected)`);
          createRadioOption("anycolor", `any color - Convert nodes tagged with any color (${nodesWithColorCount2} with any color tags)`);
          createRadioOption("nocolor", `nocolor - Convert nodes not tagged with any color (${nodesWithOutColorCount2} with no color tags)`);
          createRadioOption("color", "single color - Convert defined color tagged nodes ");
          let selectedColor = "";
          if (colorValues_length2.length > 0) {
            const usedColors = /* @__PURE__ */ new Set();
            Object.entries(colorCounts2).forEach(([color, count]) => {
              usedColors.add(color);
            });
            const colorMapping = {
              "1": "#BF616A",
              "2": "#D08770",
              "3": "#EBCB8B",
              "4": "#A3BE8C",
              "5": "#88C0D0",
              "6": "#B48EAD"
            };
            const getMappedColor = (colorValue) => {
              if (colorMapping[colorValue]) {
                return colorMapping[colorValue];
              }
              return colorValue;
            };
            const colorDropdown = radioGroup.createDiv();
            colorDropdown.addClass("dropdown-container");
            const label = colorDropdown.createEl("label", { text: "Filter by color: " });
            const select = colorDropdown.createEl("select");
            select.createEl("option", { text: "Select color", value: "" });
            usedColors.forEach((color) => {
              const count = colorCounts2[color];
              const optionEl = select.createEl("option", { text: `${color} (${count} nodes)`, value: color });
              if (!select.dataset.colorListener) {
                select.addEventListener("change", () => {
                  const val = select.value;
                  if (!val) {
                    select.style.backgroundColor = "";
                    select.style.color = "";
                    selectedColor = "";
                    return;
                  }
                  try {
                    const getRGB = (c) => {
                      var _a, _b;
                      if (c.startsWith("rgb")) {
                        const nums = (_b = (_a = c.match(/\d+/g)) == null ? void 0 : _a.map(Number)) != null ? _b : [0, 0, 0];
                        return nums.slice(0, 3);
                      }
                      let hex = c.replace("#", "").trim();
                      if (hex.length === 3) hex = hex.split("").map((ch) => ch + ch).join("");
                      const bigint = parseInt(hex, 16);
                      return [bigint >> 16 & 255, bigint >> 8 & 255, bigint & 255];
                    };
                    const [r, g, b] = getRGB(val);
                    const yiq = (r * 299 + g * 587 + b * 114) / 1e3;
                    select.style.backgroundColor = getMappedColor(val);
                    select.style.color = yiq >= 128 ? "#000" : "#fff";
                  } catch (e) {
                    select.style.backgroundColor = "";
                    select.style.color = "";
                  }
                  selectedColor = val;
                });
                select.dataset.colorListener = "1";
              }
              try {
                const getRGB = (c) => {
                  var _a, _b;
                  if (c.startsWith("rgb")) {
                    const nums = (_b = (_a = c.match(/\d+/g)) == null ? void 0 : _a.map(Number)) != null ? _b : [0, 0, 0];
                    return nums.slice(0, 3);
                  }
                  let hex = c.replace("#", "").trim();
                  if (hex.length === 3) hex = hex.split("").map((ch) => ch + ch).join("");
                  const bigint = parseInt(hex, 16);
                  return [bigint >> 16 & 255, bigint >> 8 & 255, bigint & 255];
                };
                const [r, g, b] = getRGB(color);
                const yiq = (r * 299 + g * 587 + b * 114) / 1e3;
                optionEl.style.backgroundColor = getMappedColor(color);
                optionEl.style.color = yiq >= 128 ? "#000" : "#fff";
              } catch (e) {
              }
            });
            select.onchange = () => {
              selectedColor = select.value;
            };
          }
          const buttonDiv = modal.contentEl.createDiv();
          buttonDiv.addClasses(["modal-button-container"]);
          let selectionMode2 = "all";
          buttonDiv.createEl("button", { text: "Continue" }).onclick = async () => {
            if (selectedOption == "selected" && selection.length == 0) {
              new import_obsidian.Notice(`You have selected 'Convert selected nodes only' but no nodes are selected. Please select nodes or choose another conversion mode.`);
              return;
            }
            if (selectedOption == "color" && selectedColor == "") {
              new import_obsidian.Notice(`You have selected 'Convert color tagged nodes' but no color is selected. Please select a color or choose another conversion mode.`);
              return;
            }
            if (selectedOption == "selected") {
              selectionMode2 = "selected";
            }
            if (selectedOption == "anycolor") {
              let nodeList = Object.values(colorNodeIds).flat();
              selectedNodes = nodeList.map((id) => {
                const node = full_data.nodes.find((n) => n.id === id);
                return { id, color: (node == null ? void 0 : node.color) || "none" };
              });
              selectionMode2 = "selected";
            }
            if (selectedOption == "nocolor") {
              let nodeList = Object.values(NoColorNodeIds).flat();
              selectedNodes = nodeList.map((id) => {
                const node = full_data.nodes.find((n) => n.id === id);
                return { id, color: (node == null ? void 0 : node.color) || "none" };
              });
              selectionMode2 = "selected";
            }
            if (selectedOption == "color") {
              selectedNodes = colorNodeIds[selectedColor].map((id) => ({ id, color: selectedColor }));
              selectionMode2 = "selected";
            }
            let [contents, myparsed_data] = await this.readCanvasData(canvStruct, selectedNodes, selectionMode2, selectedColor);
            const result = await this.writeCanvDocFile(contents, canvStruct, myparsed_data);
            modal.close();
          };
          buttonDiv.createEl("button", { text: "Cancel" }).onclick = () => {
            modal.close();
          };
          modal.open();
        }
      }
    });
    this.addCommand({
      id: "run-redoc",
      name: "Step 2 - Clear canvas2document target document",
      callback: async () => {
        const canvStruct = await this.readC2Dtarget();
        if (canvStruct == false) {
          new import_obsidian.Notice(`this is not a canvas2document target file`);
          return;
        }
        this.writeC2Doc(canvStruct);
      }
    });
    this.addRibbonIcon("image-down", "C2D Step 1 - Convert Canvas to draft doc", () => {
      this.app.commands.executeCommandById("canvas2document:run-conversion");
    });
    this.addRibbonIcon("file-input", "C2D Step 2 - Make cleared document", () => {
      this.app.commands.executeCommandById("canvas2document:run-redoc");
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
  }
  async readC2Dtarget() {
    let activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || !activeFile.name.includes("_fromCanvas.md")) {
      return false;
    } else {
      let mdFolderPath = path.dirname(activeFile.path);
    }
    let content = this.app.vault.cachedRead(activeFile);
    return content;
  }
  async writeC2Doc(canvStruct) {
    let activeFile = this.app.workspace.getActiveFile();
    let mdFolderPath = path.dirname(activeFile.path);
    const regex = /\!\[\[([^[\]]+)\]\]|<iframe\s+[^>]*src="(.*?)"/g;
    const matches = [];
    let match;
    while ((match = regex.exec(canvStruct)) !== null) {
      if (match[1]) {
        matches.push(match[1]);
      } else if (match[2]) {
        matches.push(match[2]);
      }
    }
    const edgelabelpattern = /<edgelabel\s+(?:data="(.*?)")?>(.*?)<\/edgelabel>/g;
    const matchesedgelabel = [];
    let matchel;
    while ((matchel = edgelabelpattern.exec(canvStruct)) !== null) {
      matchesedgelabel.push({
        data: matchel[1],
        // Captured `data` attribute (optional)
        content: matchel[2]
        // Captured inner content
      });
    }
    let doccontentstring = "> [!success] This is your converted and cleared document from Canvas2Document\n> (you can delete this infobox)\n\n";
    if (!matches) {
      return;
    }
    let textfilenames = [];
    let filenames = [];
    matches.forEach((match2) => {
      let embeddedfilename = match2.replace(/\!\[\[(.*)\]\]/, "$1");
      if (embeddedfilename.endsWith(".md")) {
        if (embeddedfilename.startsWith("./")) {
          embeddedfilename = embeddedfilename.replace("./", "");
        }
        textfilenames.push(embeddedfilename);
      }
      filenames.push(embeddedfilename);
    });
    const fileContents = await Promise.all(
      textfilenames.map(
        async (file) => [file, await this.app.vault.cachedRead(this.app.vault.getAbstractFileByPath(file))]
        //   async (file) => [file, await this.app.vault.adapter.read(file)] as const,
      )
    );
    for (const xfile of filenames) {
      if (this.settings.useedgelabels) {
        matchesedgelabel.forEach((label) => {
          if (xfile === label.data) {
            doccontentstring += '> [!info] (edge label in canvas for the following entry:) "' + label.content + '"\n\n';
          }
        });
      }
      if (xfile.endsWith(".md")) {
        const found = fileContents.find((element) => element[0] == xfile);
        const { dir, name, ext } = path.parse(xfile);
        if (!dir.endsWith("_canvas2doc-data")) {
          doccontentstring += "# " + name + "\n\n";
        }
        const frontMatterInfo = (0, import_obsidian.getFrontMatterInfo)(found[1]);
        let textfilestring = "";
        if (this.settings.usefrontmatter && frontMatterInfo.exists) {
          textfilestring = found[1];
        } else {
          textfilestring = found[1].substring(frontMatterInfo.contentStart);
        }
        doccontentstring += textfilestring + "\n\n";
      } else if (xfile.startsWith("http")) {
        doccontentstring += '<iframe width=500 height=300 src="' + xfile + '"></iframe>\n\n';
      } else {
        doccontentstring += "![[" + xfile + "]]\n\n";
      }
    }
    let docFilename;
    if (mdFolderPath == ".") {
      docFilename = activeFile.basename + "_final.md";
    } else {
      docFilename = mdFolderPath + "/" + activeFile.basename + "_final.md";
    }
    try {
      const exists = await this.fsadapter.exists(docFilename);
      if (exists && !this.settings.autooverwrite) {
        const confirmed = await new Promise((resolve) => {
          const notice = new import_obsidian.Notice("File " + docFilename + " already exists. Overwrite?", 0);
          notice.noticeEl.createEl("button", { text: "Yes" }).onclick = () => {
            notice.hide();
            resolve(true);
          };
          notice.noticeEl.createEl("button", { text: "No" }).onclick = () => {
            notice.hide();
            resolve(false);
          };
        });
        if (!confirmed) {
          return false;
        }
      }
      await this.fsadapter.write(docFilename, doccontentstring);
    } catch (e) {
      console.log("error writing the new cleared doc file " + e);
    }
    const docftab = await this.app.vault.getAbstractFileByPath(docFilename);
    try {
      await this.app.workspace.getLeaf("split").openFile(docftab);
    } catch (e) {
      console.log(e);
    }
    return;
  }
  async readCanvasStruct() {
    const canvasView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
    if ((canvasView == null ? void 0 : canvasView.getViewType()) == "canvas") {
      const canvasFile = canvasView.file;
      const path2 = canvasFile == null ? void 0 : canvasFile.path;
      let content = this.app.vault.cachedRead(canvasFile);
      return content;
    } else {
      return false;
    }
  }
  async findAllXChildren(startGeneration, myparsed_data, fileContents, handledNodes, limitrecurseNodes, runcounterfunc, runcounterforeach, selectedNodes) {
    runcounterfunc++;
    if (runcounterfunc > 30) {
      return false;
    }
    for (const child of startGeneration) {
      runcounterforeach++;
      if (runcounterforeach > myparsed_data.edges2.length) {
        return false;
      }
      const nodeentry = myparsed_data.nodes.find((entry) => entry.id === child);
      if (!handledNodes.has(child)) {
        const result = await this.formatNode(nodeentry, 6);
        if (selectionMode == "selected" && selectedNodes.length > 0) {
          const foundSelected = selectedNodes.find((entry) => entry.id === child);
          if (foundSelected) {
            fileContents.push(result);
          }
        } else {
          fileContents.push(result);
        }
        handledNodes.add(child);
      } else {
        limitrecurseNodes++;
        if (limitrecurseNodes > 30) {
          return false;
        }
      }
      let children = myparsed_data.edges2.filter((edge) => edge.fromNode === child).map((edge) => edge.toNode);
      if (children.length > 0) {
        const continueRecursion = await this.findAllXChildren(children, myparsed_data, fileContents, handledNodes, limitrecurseNodes, runcounterfunc, runcounterforeach, selectedNodes);
        if (!continueRecursion) return false;
      }
    }
    ;
    limitrecurseNodes++;
    return limitrecurseNodes <= 30;
  }
  async traverseNodes(initialNodes, myparsed_data, fileContents, handledNodes, selectedNodes, selectionMode2) {
    for (const node of initialNodes) {
      const nodeentry = myparsed_data.nodes.find((entry) => entry.id === node);
      if (!handledNodes.has(node)) {
        const result = await this.formatNode(nodeentry, 1);
        if (selectionMode2 == "selected" && selectedNodes.length > 0) {
          const foundSelected = selectedNodes.find((entry) => entry.id === node);
          if (foundSelected) {
            fileContents.push(result);
          }
        } else {
          fileContents.push(result);
        }
      }
      handledNodes.add(node);
      const children1 = myparsed_data.edges2.filter((edge) => edge.fromNode === node).map((edge) => edge.toNode);
      for (const child1 of children1) {
        const nodeentry2 = myparsed_data.nodes.find((entry) => entry.id === child1);
        if (!handledNodes.has(child1)) {
          const result = await this.formatNode(nodeentry2, 2);
          if (selectionMode2 == "selected" && selectedNodes.length > 0) {
            const foundSelected = selectedNodes.find((entry) => entry.id === child1);
            if (foundSelected) {
              fileContents.push(result);
            }
          } else {
            fileContents.push(result);
          }
        }
        handledNodes.add(child1);
        const children2 = myparsed_data.edges2.filter((edge) => edge.fromNode === child1).map((edge) => edge.toNode);
        for (const child2 of children2) {
          const nodeentry3 = myparsed_data.nodes.find((entry) => entry.id === child2);
          if (!handledNodes.has(child2)) {
            const result = await this.formatNode(nodeentry3, 3);
            if (selectionMode2 == "selected" && selectedNodes.length > 0) {
              const foundSelected = selectedNodes.find((entry) => entry.id === child2);
              if (foundSelected) {
                fileContents.push(result);
              }
            } else {
              fileContents.push(result);
            }
          }
          handledNodes.add(child2);
          const children3 = myparsed_data.edges2.filter((edge) => edge.fromNode === child2).map((edge) => edge.toNode);
          for (const child3 of children3) {
            const nodeentry4 = myparsed_data.nodes.find((entry) => entry.id === child3);
            if (!handledNodes.has(child3)) {
              const result = await this.formatNode(nodeentry4, 4);
              if (selectionMode2 == "selected" && selectedNodes.length > 0) {
                const foundSelected = selectedNodes.find((entry) => entry.id === child3);
                if (foundSelected) {
                  fileContents.push(result);
                }
              } else {
                fileContents.push(result);
              }
            }
            handledNodes.add(child3);
            const children4 = myparsed_data.edges2.filter((edge) => edge.fromNode === child3).map((edge) => edge.toNode);
            for (const child4 of children4) {
              const nodeentry5 = myparsed_data.nodes.find((entry) => entry.id === child4);
              if (!handledNodes.has(child4)) {
                const result = await this.formatNode(nodeentry5, 5);
                if (selectionMode2 == "selected" && selectedNodes.length > 0) {
                  const foundSelected = selectedNodes.find((entry) => entry.id === child4);
                  if (foundSelected) {
                    fileContents.push(result);
                  }
                } else {
                  fileContents.push(result);
                }
              }
              handledNodes.add(child4);
              const children5 = myparsed_data.edges2.filter((edge) => edge.fromNode === child4).map((edge) => edge.toNode);
              for (const child5 of children5) {
                const nodeentry6 = myparsed_data.nodes.find((entry) => entry.id === child5);
                if (!handledNodes.has(child5)) {
                  const result2 = await this.formatNode(nodeentry6, 6);
                  if (selectionMode2 == "selected" && selectedNodes.length > 0) {
                    const foundSelected = selectedNodes.find((entry) => entry.id === child5);
                    if (foundSelected) {
                      fileContents.push(result2);
                    }
                  } else {
                    fileContents.push(result2);
                  }
                }
                handledNodes.add(child5);
                const children6 = myparsed_data.edges2.filter((edge) => edge.fromNode === child5).map((edge) => edge.toNode);
                let runcounterfunc = 0;
                let runcounterforeach = 0;
                let limitrecurseNodes = 0;
                const result = await this.findAllXChildren(children6, myparsed_data, fileContents, handledNodes, limitrecurseNodes, runcounterfunc, runcounterforeach, selectedNodes);
              }
            }
          }
        }
      }
    }
  }
  async readCanvasData_pre(struct, selectedNodes) {
    const myparsed_data = JSON.parse(struct);
    const totalNodes = myparsed_data.nodes.length;
    const selectedNodesCount = selectedNodes.length;
    const colorValues = /* @__PURE__ */ new Set();
    const colorCounts = /* @__PURE__ */ new Map();
    let nodesWithColorCount = 0;
    let nodesWithOutColorCount = 0;
    const colorNodeIds = /* @__PURE__ */ new Map();
    const NoColorNodeIds = /* @__PURE__ */ new Map();
    myparsed_data.nodes.forEach((node) => {
      var _a;
      if (node.color) {
        colorValues.add(node.color);
        colorCounts.set(node.color, ((_a = colorCounts.get(node.color)) != null ? _a : 0) + 1);
        if (!colorNodeIds.has(node.color)) {
          colorNodeIds.set(node.color, []);
        }
        colorNodeIds.get(node.color).push(node.id);
        nodesWithColorCount++;
      } else {
        if (!NoColorNodeIds.has("nonecolor")) {
          NoColorNodeIds.set("nonecolor", []);
        }
        NoColorNodeIds.get("nonecolor").push(node.id);
        nodesWithOutColorCount++;
      }
    });
    return [
      totalNodes,
      selectedNodesCount,
      colorValues.size > 0 ? Array.from(colorValues) : [],
      nodesWithColorCount,
      nodesWithOutColorCount,
      Object.fromEntries(colorCounts),
      Object.fromEntries(colorNodeIds),
      Object.fromEntries(NoColorNodeIds),
      myparsed_data
    ];
  }
  async readCanvasData(struct, selectedNodes, selectionMode2, selectedColor) {
    const fileContents = [];
    let myparsed_data = JSON.parse(struct);
    const singleNodeIDs = /* @__PURE__ */ new Set();
    const groupNodes = /* @__PURE__ */ new Set();
    myparsed_data.nodes.forEach((node) => {
      if (node.type === "group") {
        groupNodes.add(node.id);
      } else {
        if (selectionMode2 == "selected" && selectedNodes.length > 0) {
          const foundSelected = selectedNodes.find((entry) => entry.id === node.id);
          if (foundSelected) {
            singleNodeIDs.add(node.id);
          }
        } else {
          singleNodeIDs.add(node.id);
        }
      }
    });
    const fromNodes = /* @__PURE__ */ new Set();
    const toNodes = /* @__PURE__ */ new Set();
    let groupClearedEdges = [];
    let resa = await myparsed_data.edges.forEach((edge) => {
      if (groupNodes.has(edge.fromNode) || groupNodes.has(edge.toNode)) {
      } else {
        fromNodes.add(edge.fromNode);
        toNodes.add(edge.toNode);
        if (selectionMode2 == "selected" && selectedNodes.length > 0) {
          const fromNodeSelected = selectedNodes.find((entry) => entry.id === edge.fromNode);
          const toNodeSelected = selectedNodes.find((entry) => entry.id === edge.toNode);
          if (fromNodeSelected && toNodeSelected) {
            groupClearedEdges.push(edge);
          }
        } else {
          groupClearedEdges.push(edge);
        }
      }
    });
    myparsed_data.edges2 = groupClearedEdges;
    let handledNodes = /* @__PURE__ */ new Set();
    const skiphandledNodes = true;
    let nodesWithoutParents = [...singleNodeIDs].filter((node) => !toNodes.has(node));
    if (nodesWithoutParents.length === 0) {
      nodesWithoutParents = [...singleNodeIDs];
    }
    const traverseresult = await this.traverseNodes(nodesWithoutParents, myparsed_data, fileContents, handledNodes, selectedNodes, selectionMode2);
    const diff = new Set([...singleNodeIDs].filter((x) => !handledNodes.has(x)));
    if (diff.size > 0) {
      const traverseresult2 = await this.traverseNodes(diff, myparsed_data, fileContents, handledNodes, selectedNodes, selectionMode2);
    }
    return [fileContents, myparsed_data];
  }
  async formatNode(node, level) {
    const id = node.id;
    const type = node.type;
    let nodefile = "";
    if (type === "file") {
      nodefile = node.file;
      const { name, ext } = path.parse(nodefile);
      if (ext === ".md") {
        return [id, type, nodefile, level, "textfile", name];
      } else if (ext === ".canvas") {
        return [id, type, nodefile, level, "embeddedcanvas", name];
      } else if (ext === ".jpg" || ext == ".jpeg" || ext === ".png" || ext === ".gif") {
        return [id, type, nodefile, level, "contentimage", name + "." + ext];
      } else if (ext === ".mp3" || ext === ".wav" || ext === ".ogg") {
        return [id, type, nodefile, level, "contentaudio", name + "." + ext];
      } else if (ext === ".mp4" || ext === ".webm") {
        return [id, type, nodefile, level, "contentvideo", name + "." + ext];
      } else if (ext === ".pdf") {
        return [id, type, nodefile, level, "contentpdf", name + "." + ext];
      } else {
        return [id, type, nodefile, level, "xfile", name + "." + ext];
      }
    } else if (type === "link") {
      if (node.url.includes("youtube")) {
        const url = node.url;
        return [id, type, url, level, "contentyoutube", node.url];
      } else {
        return [id, type, node.url, level, "contentlink", node.url];
      }
    } else if (type === "text") {
      const text = node.text;
      const textPreview = text.substring(0, 100);
      return [id, type, "node", level, text, textPreview];
    }
  }
  async writeCanvDocFile(content, convStruct, myparsed_data) {
    const canvasView = this.app.workspace.getActiveViewOfType(import_obsidian.ItemView);
    const activeFile = canvasView.file;
    let mdFolderPath = path.dirname(activeFile == null ? void 0 : activeFile.path);
    let writeworkdir = mdFolderPath + "/" + activeFile.basename + "_canvas2doc-data";
    this.fsadapter.mkdir(writeworkdir);
    let canvasFilename;
    if (mdFolderPath == ".") {
      canvasFilename = activeFile.basename + "_fromCanvas.md";
    } else {
      canvasFilename = mdFolderPath + "/" + activeFile.basename + "_fromCanvas.md";
    }
    let contentString = "> [!info] This is an automatically generated document from Plugin [Canvas2Document](https://github.com/slnsys/obsidian-canvas2document)\n> arrange the document as you need with the outline, then call *Clear canvas2document target document*\n\n";
    for (const element of content) {
      let cnfname = "";
      let heading = "";
      for (let i = 0; i < element[3]; i++) {
        heading += "#";
      }
      if (element[1] == "text") {
        cnfname = writeworkdir + "/newdoc-node_" + element[0] + "_fromCanvas.md";
        contentString += "\n\n" + heading + " _card " + element[5] + "\n";
        contentString += element[2] + " ^" + element[0] + "\n\n";
        contentString += "> [!tip] link navigation from the canvas\n";
        let foundsometolinks = false;
        let foundsomefromlinks = false;
        for (const edge of myparsed_data.edges2) {
          if (edge.fromNode == element[0]) {
            const found = content.find((element2) => element2[0] == edge.toNode);
            const firstline = found[5].split("\n")[0];
            const found5 = firstline.replace(/#/g, "");
            contentString += "> linking to: [[#^" + edge.toNode + "|" + found5 + "]]\n";
            foundsometolinks = true;
          }
          if (edge.toNode == element[0]) {
            const found = content.find((element2) => element2[0] == edge.fromNode);
            const firstline = found[5].split("\n")[0];
            const found5 = firstline.replace(/#/g, "");
            if (edge.label != void 0) {
              const sanitizedLabel = edge.label.replace(/\n/g, " - ");
              contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + ']] ("<edgelabel data="' + cnfname + '">' + sanitizedLabel + '</edgelabel>")\n';
            } else {
              contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + "]]\n";
            }
            foundsomefromlinks = true;
          }
        }
        if (!foundsomefromlinks) {
          contentString += "> No links from this node\n";
        }
        if (!foundsometolinks) {
          contentString += "> No links to other nodes from this node\n";
        }
        contentString += "\n ![[" + cnfname + "]]\n\n";
        let canvasnodeFile;
        try {
          let cnfabst2 = this.app.vault.getAbstractFileByPath(cnfname);
          await this.fsadapter.write(cnfname, element[4]);
        } catch (e) {
          console.log(e);
          return;
        }
      } else if (element[1] == "link") {
        contentString += "\n\n" + heading + " _link " + element[5] + "\n";
        contentString += element[2] + " ^" + element[0] + "\n\n";
        contentString += "> [!tip] link navigation from the canvas\n";
        let foundsometolinks = false;
        let foundsomefromlinks = false;
        for (const edge of myparsed_data.edges2) {
          if (edge.fromNode == element[0]) {
            const found = content.find((element2) => element2[0] == edge.toNode);
            const firstline = found[5].split("\n")[0];
            const found5 = firstline.replace(/#/g, "");
            contentString += "> linking to: [[#^" + edge.toNode + "|" + found5 + "]]\n";
            foundsometolinks = true;
          }
          if (edge.toNode == element[0]) {
            const found = content.find((element2) => element2[0] == edge.fromNode);
            const firstline = found[5].split("\n")[0];
            const found5 = firstline.replace(/#/g, "");
            if (edge.label != void 0) {
              const sanitizedLabel = edge.label.replace(/\n/g, " - ");
              contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + ']] ("<edgelabel data="' + element[2] + '">' + sanitizedLabel + '</edgelabel>")\n';
            } else {
              contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + "]]\n";
            }
            foundsomefromlinks = true;
          }
        }
        if (!foundsomefromlinks) {
          contentString += "> No links from this node\n";
        }
        if (!foundsometolinks) {
          contentString += "> No links to other nodes from this node\n";
        }
        if (element[4] == "contentyoutube") {
          contentString += "\n ![](" + element[2] + ")\n\n";
        } else if (element[4] == "contentlink") {
          contentString += '\n <iframe width=500 height=300 src="' + element[2] + '"></iframe>\n\n';
        }
      } else if (element[1] == "file") {
        if (element[4] == "contentimage" || element[4] == "contentpdf") {
          contentString += "\n\n" + heading + " _Media " + element[5] + "\n";
          contentString += element[2] + " ^" + element[0] + "\n\n";
          contentString += "> [!tip] link navigation from the canvas\n";
          let foundsometolinks = false;
          let foundsomefromlinks = false;
          for (const edge of myparsed_data.edges2) {
            if (edge.fromNode == element[0]) {
              const found = content.find((element2) => element2[0] == edge.toNode);
              const firstline = found[5].split("\n")[0];
              const found5 = firstline.replace(/#/g, "");
              contentString += "> linking to: [[#^" + edge.toNode + "|" + found5 + "]]\n";
              foundsometolinks = true;
            }
            if (edge.toNode == element[0]) {
              const found = content.find((element2) => element2[0] == edge.fromNode);
              const firstline = found[5].split("\n")[0];
              const found5 = firstline.replace(/#/g, "");
              if (edge.label != void 0) {
                const sanitizedLabel = edge.label.replace(/\n/g, " - ");
                contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + ']] ("<edgelabel data="' + element[2] + '">' + sanitizedLabel + '</edgelabel>")\n';
              } else {
                contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + "]]\n";
              }
              foundsomefromlinks = true;
            }
          }
          if (!foundsomefromlinks) {
            contentString += "> No links from this node\n";
          }
          if (!foundsometolinks) {
            contentString += "> No links to other nodes from this node\n";
          }
          if (element[4] == "contentpdf") {
            contentString += "\n ![[" + element[2] + "]]\n\n";
          } else if (element[4] == "contentimage") {
            contentString += "\n ![[" + element[2] + "]]\n\n";
          }
        } else {
          contentString += "\n\n" + heading + " _noteFile " + element[5] + "\n";
          contentString += element[2] + " ^" + element[0] + "\n\n";
          contentString += "> [!tip] link navigation from the canvas\n";
          let foundsometolinks = false;
          let foundsomefromlinks = false;
          for (const edge of myparsed_data.edges2) {
            if (edge.fromNode == element[0]) {
              const found = content.find((element2) => element2[0] == edge.toNode);
              const firstline = found[5].split("\n")[0];
              const found5 = firstline.replace(/#/g, "");
              contentString += "> linking to: [[#^" + edge.toNode + "|" + found5 + "]]\n";
              foundsometolinks = true;
            }
            if (edge.toNode == element[0]) {
              const found = content.find((element2) => element2[0] == edge.fromNode);
              const firstline = found[5].split("\n")[0];
              const found5 = firstline.replace(/#/g, "");
              if (edge.label != void 0) {
                const sanitizedLabel = edge.label.replace(/\n/g, " - ");
                contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + ']] ("<edgelabel data="' + element[2] + '">' + sanitizedLabel + '</edgelabel>")\n';
              } else {
                contentString += "> linked from: [[#^" + edge.fromNode + "|" + found5 + "]]\n";
              }
              foundsomefromlinks = true;
            }
          }
          if (!foundsomefromlinks) {
            contentString += "> No links from this node\n";
          }
          if (!foundsometolinks) {
            contentString += "> No links to other nodes from this node\n";
          }
          contentString += "\n ![[" + element[2] + "]]\n\n";
        }
      }
    }
    try {
      const exists = await this.fsadapter.exists(canvasFilename);
      if (exists && !this.settings.autooverwrite) {
        const confirmed = await new Promise((resolve) => {
          const notice = new import_obsidian.Notice("File " + canvasFilename + " already exists. Overwrite?", 0);
          notice.noticeEl.createEl("button", { text: "Yes" }).onclick = () => {
            notice.hide();
            resolve(true);
          };
          notice.noticeEl.createEl("button", { text: "No" }).onclick = () => {
            notice.hide();
            resolve(false);
          };
        });
        if (!confirmed) {
          return false;
        }
      }
      await this.fsadapter.write(canvasFilename, contentString);
    } catch (e) {
      console.log("error writing the new doc file " + e);
    }
    const cnfabst = await this.app.vault.getAbstractFileByPath(canvasFilename);
    try {
      await this.app.workspace.getLeaf("split").openFile(cnfabst);
    } catch (e) {
      console.log(e);
    }
    return true;
  }
};


/* nosourcemap */